<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Differentiation timing score</title>
  <meta name="description" content="PCA-based scoring of differentiation timing from bulk RNA-seq time-course data." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Differentiation timing score" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="PCA-based scoring of differentiation timing from bulk RNA-seq time-course data." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Differentiation timing score" />
  
  <meta name="twitter:description" content="PCA-based scoring of differentiation timing from bulk RNA-seq time-course data." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  


<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path=""><a href="#introduction"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path=""><a href="#function-inputs"><i class="fa fa-check"></i><b>2</b> Function inputs</a></li>
<li class="chapter" data-level="3" data-path=""><a href="#reference-dataset"><i class="fa fa-check"></i><b>3</b> Reference dataset</a></li>
<li class="chapter" data-level="4" data-path=""><a href="#scoring-workflow"><i class="fa fa-check"></i><b>4</b> Scoring workflow</a>
<ul>
<li class="chapter" data-level="4.1" data-path=""><a href="#select-temporal-genes"><i class="fa fa-check"></i><b>4.1</b> Select temporal genes</a></li>
<li class="chapter" data-level="4.2" data-path=""><a href="#fit-the-pca-reference-space"><i class="fa fa-check"></i><b>4.2</b> Fit the PCA reference space</a></li>
<li class="chapter" data-level="4.3" data-path=""><a href="#build-and-score-the-reference-trajectory"><i class="fa fa-check"></i><b>4.3</b> Build and score the reference trajectory</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path=""><a href="#leave-one-out-validation-of-maturation-score"><i class="fa fa-check"></i><b>5</b> Leave-one-out validation of maturation score</a></li>
<li class="chapter" data-level="6" data-path=""><a href="#interpreting-results"><i class="fa fa-check"></i><b>6</b> Interpreting results</a>
<ul>
<li class="chapter" data-level="6.1" data-path=""><a href="#interpreting-scores"><i class="fa fa-check"></i><b>6.1</b> Interpreting scores</a></li>
<li class="chapter" data-level="6.2" data-path=""><a href="#adapting-maturation-score"><i class="fa fa-check"></i><b>6.2</b> Adapting maturation score</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path=""><a href="#references"><i class="fa fa-check"></i><b>7</b> References</a></li>
<li class="chapter" data-level="8" data-path=""><a href="#session-information"><i class="fa fa-check"></i><b>8</b> Session information</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Differentiation timing score</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="header">
<h1 class="title">Differentiation timing score</h1>
</div>
<div class="tutorial-title-block">
<h1 class="title">
Differentiation timing score
</h1>
<div class="tutorial-subtitle">
PCA-based scoring of differentiation timing from bulk RNA-seq time-course data
</div>
<div class="tutorial-meta-block">
<div>
<span>Author:</span> Zoheb Khan
</div>
<div>
<span>Created:</span> 2025-08-29
</div>
<div>
<span>Modified:</span> 2026-08-10
</div>
<div>
<span>Compiled:</span> 2026-08-10
</div>
<div>
<span>Environment:</span> R 4.6.1; Bioconductor 3.23
</div>
<div>
<span>Dependencies:</span> AnnotationDbi 1.74.0; bookdown 0.47; circlize 0.4.18; clusterProfiler 4.20.0; ComplexHeatmap 2.28.0; DESeq2 1.52.0; edgeR 4.10.1; ggplot2 4.0.3; ggrepel 0.9.8; knitr 1.51; org.Hs.eg.db 3.23.1; patchwork 1.3.2; ragg 1.5.2; scales 1.4.0; systemfonts 1.3.2; viridis 0.6.5
</div>
<div>
<span>Source:</span> <a href="https://github.com/ZohebKhan1/pca-maturation-scoring">github.com/ZohebKhan1/pca-maturation-scoring</a>
</div>
</div>
</div>
<div id="introduction" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">1</span> Introduction<a href="#introduction" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Bulk RNA-seq differentiation studies usually record samples at discrete timepoints. Samples collected on the same day can still be at different stages of differentiation. This tutorial shows how to use an ordered reference time course to estimate a continuous position for each sample.</p>
<p>The workflow has three stages:</p>
<ol style="list-style-type: decimal">
<li>Select genes whose expression changes across the reference time course.</li>
<li>Fit a PCA space to the reference timepoint means and connect those means into a trajectory.</li>
<li>Project each sample onto the trajectory.</li>
</ol>
<p>The workflow returns a predicted time on the reference scale, a differentiation score scaled from 0 to 1 between the reference endpoints, and squared distance from the trajectory. These outputs describe position within the selected reference; they are not measurements of absolute biological age.</p>
</div>
<div id="function-inputs" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">2</span> Function inputs<a href="#function-inputs" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><code>get_temporal_genes()</code> uses integer-like raw counts, VST expression, and sample metadata. It selects genes inside the reference cohort. <code>score_differentiation_timing()</code> uses normalized expression and those selected genes to fit the reference PCA and trajectory.</p>
<p>For a reference-only analysis, the scorer uses all supplied samples as the reference. To score new samples, provide <code>reference_samples</code> so that PCA and the trajectory use only the independent reference cohort. Reference samples must have finite timepoints. New non-reference samples can have missing timepoints because the scorer predicts their time rather than using an observed time.</p>
<p>The scorer fits PCA to timepoint means, centers genes, and does not scale them to unit variance. It retains the smallest number of PCs that explain at least 99% of the variance between reference timepoint means. The PCA sign is arbitrary; reversing a PC for a figure does not change distances or scores.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">download.file</span>(</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a>  <span class="st">&#39;https://raw.githubusercontent.com/ZohebKhan1/pca-maturation-scoring/main/functions/get_temporal_genes.R&#39;</span>,</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a>  <span class="st">&#39;get_temporal_genes.R&#39;</span>,</span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a>  <span class="at">mode =</span> <span class="st">&#39;wb&#39;</span></span>
<span id="cb1-5"><a href="#cb1-5" tabindex="-1"></a>)</span>
<span id="cb1-6"><a href="#cb1-6" tabindex="-1"></a><span class="fu">download.file</span>(</span>
<span id="cb1-7"><a href="#cb1-7" tabindex="-1"></a>  <span class="st">&#39;https://raw.githubusercontent.com/ZohebKhan1/pca-maturation-scoring/main/functions/score_differentiation_timing.R&#39;</span>,</span>
<span id="cb1-8"><a href="#cb1-8" tabindex="-1"></a>  <span class="st">&#39;score_differentiation_timing.R&#39;</span>,</span>
<span id="cb1-9"><a href="#cb1-9" tabindex="-1"></a>  <span class="at">mode =</span> <span class="st">&#39;wb&#39;</span></span>
<span id="cb1-10"><a href="#cb1-10" tabindex="-1"></a>)</span>
<span id="cb1-11"><a href="#cb1-11" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&#39;get_temporal_genes.R&#39;</span>)</span>
<span id="cb1-13"><a href="#cb1-13" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&#39;score_differentiation_timing.R&#39;</span>)</span></code></pre></div>
</div>
<div id="reference-dataset" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">3</span> Reference dataset<a href="#reference-dataset" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>The example uses processed data from <a href="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE122380">NCBI GEO accession GSE122380</a>, a bulk RNA-seq time course of human induced pluripotent stem cell differentiation into cardiomyocytes. The reference contains 192 samples from 13 cell lines collected across differentiation days 1 through 15.</p>
<p>The repository provides aligned metadata, a raw gene-count matrix, and a VST expression matrix. The tutorial starts from these processed objects. It does not reconstruct the upstream FASTQ processing, read alignment, gene quantification, or VST transformation.</p>
<div class="table-scroll" role="region" aria-label="Samples and cell lines by differentiation day" tabindex="0">
<table class="sample-summary-table">
<caption>
<span id="tab:sample-summary-table">Table 3.1: </span>Samples and represented cell lines by differentiation day.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Metric
</th>
<th style="text-align:right;">
D1
</th>
<th style="text-align:right;">
D2
</th>
<th style="text-align:right;">
D3
</th>
<th style="text-align:right;">
D4
</th>
<th style="text-align:right;">
D5
</th>
<th style="text-align:right;">
D6
</th>
<th style="text-align:right;">
D7
</th>
<th style="text-align:right;">
D8
</th>
<th style="text-align:right;">
D9
</th>
<th style="text-align:right;">
D10
</th>
<th style="text-align:right;">
D11
</th>
<th style="text-align:right;">
D12
</th>
<th style="text-align:right;">
D13
</th>
<th style="text-align:right;">
D14
</th>
<th style="text-align:right;">
D15
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Samples
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
13
</td>
</tr>
<tr>
<td style="text-align:left;">
Cell lines
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
13
</td>
</tr>
</tbody>
</table>
</div>
<p>Figure 1 shows the time-course structure with a PCA of the most variable VST genes and a correlation matrix of day-mean expression profiles. Both views show whether the reference has an ordered expression pattern before the trajectory model is fitted.</p>
<div id="fig-reference-overview" class="figure-anchor">

</div>
<p><img class="tutorial-figure" src="assets/figures/GSE122380_reference_pca_and_day_correlation.png" alt="PCA of the reference samples and a day-level expression correlation heatmap." style="width:96%;"></p>
<div class="tutorial-figure-caption">
<strong>Figure 1.</strong> GSE122380 reference time course and day-level expression correlation. <strong>a.</strong> PCA using the top 10% most variable VST genes, colored by differentiation day. <strong>b.</strong> Pearson correlation between day-mean profiles from the same variable-gene set.
</div>
<p>The day ordering supports fitting a reference trajectory. This overview PCA is separate from the scoring PCA, which uses the selected temporal genes and reference timepoint means.</p>
</div>
<div id="scoring-workflow" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">4</span> Scoring workflow<a href="#scoring-workflow" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="select-temporal-genes" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Select temporal genes<a href="#select-temporal-genes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><code>get_temporal_genes()</code> applies three filters to the reference samples. The function uses raw counts for the expression filter and DESeq2 LRT, and it uses VST expression for the final range filter. A gene must pass every filter to enter the trajectory model.</p>
<ol style="list-style-type: decimal">
<li><strong>Expression filter.</strong> The function calculates TMM-normalized CPM internally. For each gene, it calculates the mean CPM at each reference timepoint and keeps the gene when its largest timepoint mean reaches the expression threshold.</li>
<li><strong>DESeq2 likelihood-ratio test.</strong> The full model includes categorical time and any requested adjustment covariates. The reduced model contains the adjustment covariates without time. Genes with an adjusted LRT p-value below the selected threshold continue to the final filter.</li>
<li><strong>VST-range filter.</strong> The function calculates the mean VST expression at each reference timepoint and keeps genes whose range across those means reaches the selected threshold.</li>
</ol>
<p>The LRT tests whether adding categorical time improves the count model. If the full and reduced models have maximized log likelihoods <code>ell_full</code> and <code>ell_reduced</code>, the likelihood-ratio statistic is</p>
<p><span class="math display">\[
\mathrm{LR} = 2(\ell_\mathrm{full} - \ell_\mathrm{reduced}).
\]</span></p>
<p>The test does not assume that expression changes linearly with time. With no adjustment covariates, the reduced model is <code>~ 1</code>. For GSE122380, <code>cell_line</code> is included in both models so that the time test accounts for cell-line differences.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&#39;functions/get_temporal_genes.R&#39;</span>)</span>
<span id="cb2-2"><a href="#cb2-2" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" tabindex="-1"></a>temporal_selection <span class="ot">&lt;-</span> <span class="fu">get_temporal_genes</span>(</span>
<span id="cb2-4"><a href="#cb2-4" tabindex="-1"></a>  <span class="at">raw_counts =</span> counts,</span>
<span id="cb2-5"><a href="#cb2-5" tabindex="-1"></a>  <span class="at">vst_expression =</span> vst,</span>
<span id="cb2-6"><a href="#cb2-6" tabindex="-1"></a>  <span class="at">metadata =</span> metadata,</span>
<span id="cb2-7"><a href="#cb2-7" tabindex="-1"></a>  <span class="at">sample_id_col =</span> <span class="st">&#39;sample_id&#39;</span>,</span>
<span id="cb2-8"><a href="#cb2-8" tabindex="-1"></a>  <span class="at">time_col =</span> <span class="st">&#39;day_numeric&#39;</span>,</span>
<span id="cb2-9"><a href="#cb2-9" tabindex="-1"></a>  <span class="at">adjustment_covariates =</span> <span class="st">&#39;cell_line&#39;</span></span>
<span id="cb2-10"><a href="#cb2-10" tabindex="-1"></a>)</span>
<span id="cb2-11"><a href="#cb2-11" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" tabindex="-1"></a>temporal_genes <span class="ot">&lt;-</span> temporal_selection<span class="sc">$</span>temporal_genes</span></code></pre></div>
<p>If gene selection should use one reference group, supply <code>reference_group_col</code> and <code>reference_group_value</code> together. The function then restricts the expression filter, LRT, and VST-range filter to samples with that value. This option controls which samples enter selection; it is not a DESeq2 coefficient reference level.</p>
<p>For the GSE122380 reference, the expression, LRT, and VST-range settings produce the counts shown in Table 4.1. For another study, set thresholds from its library sizes, sample size, timepoint coverage, and design.</p>
<table class="sample-summary-table">
<caption>
<span id="tab:lrt-summary-table">Table 4.1: </span>Sequential temporal-gene filtering.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Metric
</th>
<th style="text-align:right;">
Value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Genes in the aligned count/VST input
</td>
<td style="text-align:right;">
13,615
</td>
</tr>
<tr>
<td style="text-align:left;">
Genes with maximum day-mean TMM CPM &gt;= 10
</td>
<td style="text-align:right;">
11,411
</td>
</tr>
<tr>
<td style="text-align:left;">
Genes passing LRT adjusted p-value &lt; 1e-7
</td>
<td style="text-align:right;">
10,863
</td>
</tr>
<tr>
<td style="text-align:left;">
Genes passing all filters and used for scoring
</td>
<td style="text-align:right;">
8,215
</td>
</tr>
</tbody>
</table>
<p>The heatmap shows the first 1,500 final temporal genes, ordered by the LRT results. The scoring model uses the complete temporal-gene set, not only the genes shown in this figure.</p>
<div id="fig-temporal-heatmap" class="figure-anchor">

</div>
<p><img class="tutorial-figure" src="assets/figures/GSE122380_temporal_heatmap.png" alt="Heatmap of 1500 temporal genes across all samples, ordered by differentiation day." style="width:92%;"></p>
<div class="tutorial-figure-caption">
<strong>Figure 2.</strong> Heatmap of the 1,500 displayed temporal genes across the reference samples, ordered by differentiation day.
</div>
<p>The displayed genes show expression changes across the reference. The display order and heatmap subset are for inspection; PCA, scoring, and validation use all selected temporal genes.</p>
<p>The four clusters in Figure 3 summarize expression patterns in the displayed heatmap genes. They annotate the displayed patterns only. Cluster membership does not change temporal-gene selection, PCA fitting, scoring, or validation. The GO analysis uses the displayed genes as its enrichment universe.</p>
<div id="fig-temporal-clusters" class="figure-anchor">

</div>
<p><img class="tutorial-figure" src="assets/figures/GSE122380_temporal_clusters.png" alt="Four temporal expression clusters with their enriched GO biological processes." style="width:96%;"></p>
<div class="tutorial-figure-caption">
<strong>Figure 3.</strong> Temporal clusters and GO enrichment for the 1,500 heatmap genes. Each row pairs a cluster trajectory with its top enriched GO Biological Process terms.
</div>
<p>The cluster trajectories summarize expression patterns. They are not additional differentiation scores.</p>
</div>
<div id="fit-the-pca-reference-space" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Fit the PCA reference space<a href="#fit-the-pca-reference-space" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The scoring PCA is trained on reference timepoint means rather than on individual samples. This makes the reference path represent the average expression at each observed timepoint and prevents samples with larger within-timepoint variation from defining the path directly.</p>
<p>Let <span class="math inline">\(\mathbf{x}_i\)</span> be the normalized expression vector for sample <span class="math inline">\(i\)</span>, restricted to the selected temporal genes. For a reference timepoint <span class="math inline">\(t\)</span>, let <span class="math inline">\(\bar{\mathbf{x}}_t\)</span> be the mean vector across its reference samples:</p>
<p><span class="math display">\[
\bar{\mathbf{x}}_t = \frac{1}{n_t}\sum_{i:\,t_i=t} \mathbf{x}_i.
\tag{1}
\]</span></p>
<p>The function fits centered, unscaled PCA to the collection of <span class="math inline">\(\bar{\mathbf{x}}_t\)</span> vectors. Let <span class="math inline">\(\boldsymbol{\mu}\)</span> be the mean of those timepoint means and let <span class="math inline">\(W\)</span> contain the retained PCA loading vectors. The PCA coordinates for any sample are</p>
<p><span class="math display">\[
\mathbf{z}_i = (\mathbf{x}_i - \boldsymbol{\mu})W.
\tag{2}
\]</span></p>
<p>The same transformation maps both reference and non-reference samples into the reference space. In the GSE122380 fit, seven PCs meet the 99% variance target. The number can change when the reference cohort or temporal-gene set changes.</p>
<div id="fig-pca-day" class="figure-anchor">

</div>
<p><img class="tutorial-figure" src="assets/figures/GSE122380_pca_day.png" alt="PCA and PC1 versus day for all temporal genes and early and late cluster subsets." style="width:96%;"></p>
<div class="tutorial-figure-caption">
<strong>Figure 4.</strong> Individual samples projected into centered, unscaled PCA spaces learned from timepoint means for the full temporal set and two cluster subsets. C1+C2 and C3+C4 are shown for comparison, not as alternative models.
</div>
<p>The full temporal-gene panel shows the PCA space used for scoring. The cluster panels show how selected expression subsets relate to the same time course; they do not replace the full temporal-gene model.</p>
<p>Use PCA loadings to inspect which genes contribute to the reference axes. Figure 5 labels the largest PC1 and PC2 loadings and tests the strongest PC1 loadings for GO enrichment. The enrichment annotates the PCA axes; it is not part of the timing score.</p>
<div id="fig-pc1-validation" class="figure-anchor">

</div>
<p><img class="tutorial-figure" src="assets/figures/GSE122380_pc1_validation.png" alt="Top PCA loading genes and GO enrichment for positive and negative PC1 loadings." style="width:96%;"></p>
<div class="tutorial-figure-caption">
<strong>Figure 5.</strong> PCA loading genes and GO enrichment. <strong>a-b.</strong> The ten largest positive and negative PC1 and PC2 loading genes. Ambiguous Ensembl-to-symbol mappings retain the Ensembl ID. <strong>c-d.</strong> GO enrichment among the 500 strongest negative and positive PC1 loadings.
</div>
<p>The sign of a PCA axis is arbitrary. The build flips PC1 for figure readability when needed, but this does not change Euclidean distances or sample scores.</p>
</div>
<div id="build-and-score-the-reference-trajectory" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Build and score the reference trajectory<a href="#build-and-score-the-reference-trajectory" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The scorer converts the ordered reference timepoint means into centroids in the retained PCA space. Adjacent centroids define finite line segments. A sample can therefore follow a path that bends across several PCs instead of being ranked by PC1 alone.</p>
<p>For one segment, let <span class="math inline">\(\mathbf{a}\)</span> and <span class="math inline">\(\mathbf{b}\)</span> be its start and end centroids, and let <span class="math inline">\(\mathbf{z}\)</span> be a sample’s PCA coordinate. The segment direction is <span class="math inline">\(\mathbf{v}=\mathbf{b}-\mathbf{a}\)</span>. The closest point on the finite segment is</p>
<p><span class="math display">\[
\alpha = \operatorname{clip}_{[0,1]}
\left(
\frac{\langle \mathbf{z}-\mathbf{a},\mathbf{v}\rangle}
     {\langle \mathbf{v},\mathbf{v}\rangle}
\right),
\qquad
\mathbf{q}=\mathbf{a}+\alpha\mathbf{v}.
\tag{3}
\]</span></p>
<p>The clipping keeps <span class="math inline">\(\alpha\)</span> between 0 and 1, so the projection stays on the segment rather than extending beyond a reference endpoint. The scorer evaluates every segment and uses the one with the smallest squared distance <span class="math inline">\(\lVert\mathbf{z}-\mathbf{q}\rVert^2\)</span>. It then interpolates time along that segment:</p>
<p><span class="math display">\[
\widehat{t}=t_a+\alpha(t_b-t_a),
\qquad
s=\frac{\widehat{t}-t_{\min}}{t_{\max}-t_{\min}}.
\tag{4}
\]</span></p>
<p>Here <span class="math inline">\(t_a\)</span> and <span class="math inline">\(t_b\)</span> are the segment endpoint times. The score is 0 at the earliest reference time and 1 at the latest reference time. Because the projection is clipped to finite segments, the reported time stays within the reference time range.</p>
<p>Zero-length segments are omitted. A trajectory that folds back near itself can produce ambiguous nearest-segment assignments; review squared distance and the trajectory plot when adapting the method.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&#39;functions/score_differentiation_timing.R&#39;</span>)</span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" tabindex="-1"></a>timing_fit <span class="ot">&lt;-</span> <span class="fu">score_differentiation_timing</span>(</span>
<span id="cb3-4"><a href="#cb3-4" tabindex="-1"></a>  <span class="at">expression_matrix =</span> vst,</span>
<span id="cb3-5"><a href="#cb3-5" tabindex="-1"></a>  <span class="at">metadata =</span> metadata,</span>
<span id="cb3-6"><a href="#cb3-6" tabindex="-1"></a>  <span class="at">temporal_genes =</span> temporal_genes,</span>
<span id="cb3-7"><a href="#cb3-7" tabindex="-1"></a>  <span class="at">sample_id_col =</span> <span class="st">&#39;sample_id&#39;</span>,</span>
<span id="cb3-8"><a href="#cb3-8" tabindex="-1"></a>  <span class="at">time_col =</span> <span class="st">&#39;day_numeric&#39;</span></span>
<span id="cb3-9"><a href="#cb3-9" tabindex="-1"></a>)</span>
<span id="cb3-10"><a href="#cb3-10" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" tabindex="-1"></a>timing_fit<span class="sc">$</span>scores[, <span class="fu">c</span>(</span>
<span id="cb3-12"><a href="#cb3-12" tabindex="-1"></a>  <span class="st">&#39;sample_id&#39;</span>,</span>
<span id="cb3-13"><a href="#cb3-13" tabindex="-1"></a>  <span class="st">&#39;observed_time&#39;</span>,</span>
<span id="cb3-14"><a href="#cb3-14" tabindex="-1"></a>  <span class="st">&#39;predicted_time&#39;</span>,</span>
<span id="cb3-15"><a href="#cb3-15" tabindex="-1"></a>  <span class="st">&#39;differentiation_score&#39;</span>,</span>
<span id="cb3-16"><a href="#cb3-16" tabindex="-1"></a>  <span class="st">&#39;squared_distance&#39;</span></span>
<span id="cb3-17"><a href="#cb3-17" tabindex="-1"></a>)]</span></code></pre></div>
<p>Figure 6 shows the fitted path in the first two PCs. The path is defined in all retained PCs; the figure is a two-dimensional view.</p>
<div id="fig-timing-polyline" class="figure-anchor">

</div>
<p><img class="tutorial-figure" src="assets/figures/GSE122380_timing_polyline.png" alt="Samples and the ordered day-centroid polyline in the first two principal components." style="width:86%;"></p>
<div class="tutorial-figure-caption">
<strong>Figure 6.</strong> Differentiation trajectory in reference PCA space. Black points are day centroids; arrows connect them in day order. The day 1 and day 15 centroids anchor scores 0 and 1.
</div>
<p>The centroids define the reference path. The path is not a single-axis ranking and does not assume that the samples move at a constant rate between observed timepoints.</p>
<p>Figure 7 shows the scores of the reference samples projected back onto the fitted path. This is a calibration view because the same reference samples define the PCA and trajectory.</p>
<div id="fig-score-by-day" class="figure-anchor">

</div>
<p><img class="tutorial-figure" src="assets/figures/GSE122380_score_by_day.png" alt="Differentiation timing scores across observed differentiation days." style="width:96%;"></p>
<div class="tutorial-figure-caption">
<strong>Figure 7.</strong> Reference-sample differentiation timing scores by observed day. Dashed lines mark the bounded reference endpoints at 0 and 1.
</div>
<p>The spread within a day shows how much samples differ around the reference trajectory. It is not an out-of-sample accuracy estimate.</p>
</div>
</div>
<div id="leave-one-out-validation-of-maturation-score" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">5</span> Leave-one-out validation of maturation score<a href="#leave-one-out-validation-of-maturation-score" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>The validation tests whether a trajectory trained without one cell line can predict the samples from that cell line. For each held-out cell line, the workflow:</p>
<ol style="list-style-type: decimal">
<li>removes that cell line from the training reference;</li>
<li>selects temporal genes using the remaining cell lines;</li>
<li>fits the PCA and centroid trajectory using the remaining cell lines; and</li>
<li>projects the held-out samples onto that fitted trajectory.</li>
</ol>
<p>The count-based DESeq2 LRT is refit in every fold. The tracked VST matrix is shared across folds because the upstream VST transformation is not available in the repository. The validation therefore measures internal transfer within this processed cohort, conditional on the tracked VST matrix. It is not an external validation study.</p>
<p>The validation function also labels fold-specific genes as maturation or progenitor genes according to the sign of their Spearman correlation with time. Those labels annotate genes only. The reported accuracy metrics use the complete temporal-gene set.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&#39;functions/get_temporal_genes.R&#39;</span>)</span>
<span id="cb4-2"><a href="#cb4-2" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&#39;functions/score_differentiation_timing.R&#39;</span>)</span>
<span id="cb4-3"><a href="#cb4-3" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&#39;functions/run_loo_maturation.R&#39;</span>)</span>
<span id="cb4-4"><a href="#cb4-4" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" tabindex="-1"></a>loo_validation <span class="ot">&lt;-</span> <span class="fu">run_loo_maturation</span>(</span>
<span id="cb4-6"><a href="#cb4-6" tabindex="-1"></a>  <span class="at">counts =</span> counts,</span>
<span id="cb4-7"><a href="#cb4-7" tabindex="-1"></a>  <span class="at">vst =</span> vst,</span>
<span id="cb4-8"><a href="#cb4-8" tabindex="-1"></a>  <span class="at">metadata =</span> metadata</span>
<span id="cb4-9"><a href="#cb4-9" tabindex="-1"></a>)</span>
<span id="cb4-10"><a href="#cb4-10" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" tabindex="-1"></a>loo_validation<span class="sc">$</span>summary</span></code></pre></div>
<p>All 13 cell lines contribute to the validation. Cell line <code>19190</code> is omitted only from the per-cell-line figure to keep the display at 3 by 4 panels.</p>
<table class="sample-summary-table">
<caption>
<span id="tab:loo-summary-table">Table 5.1: </span>Leave-one-cell-line-out validation summary.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Metric
</th>
<th style="text-align:right;">
Value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Held-out cell lines
</td>
<td style="text-align:right;">
13
</td>
</tr>
<tr>
<td style="text-align:left;">
Held-out samples
</td>
<td style="text-align:right;">
192
</td>
</tr>
<tr>
<td style="text-align:left;">
Correlation between actual and predicted day
</td>
<td style="text-align:right;">
0.979
</td>
</tr>
<tr>
<td style="text-align:left;">
Squared Pearson correlation
</td>
<td style="text-align:right;">
0.959
</td>
</tr>
<tr>
<td style="text-align:left;">
Mean absolute error
</td>
<td style="text-align:right;">
0.55 days
</td>
</tr>
<tr>
<td style="text-align:left;">
Median absolute error
</td>
<td style="text-align:right;">
0.30 days
</td>
</tr>
<tr>
<td style="text-align:left;">
Predictions within 1 day
</td>
<td style="text-align:right;">
82.3%
</td>
</tr>
<tr>
<td style="text-align:left;">
Predictions within 2 days
</td>
<td style="text-align:right;">
97.9%
</td>
</tr>
</tbody>
</table>
<p>In this reference, held-out predictions correlate 0.979 with observed days. The median absolute error is 0.30 days, and 82.3% of predictions are within one day. These values describe this cohort and this processing pipeline; they are not universal performance guarantees.</p>
<div id="fig-loo-cell-line-predictions" class="figure-anchor">

</div>
<p><img class="tutorial-figure" src="assets/figures/GSE122380_loo_cell_line_predictions.png" alt="Predicted versus observed day trajectories for twelve displayed held-out cell lines." style="width:96%;"></p>
<div class="tutorial-figure-caption">
<strong>Figure 8.</strong> Held-out predictions for 12 displayed cell lines. Each panel reports Pearson <span class="math inline">\(r\)</span> and its square for that line; neither quantity is a predictive <span class="math inline">\(R^2\)</span> statistic.
</div>
<p>Performance varies across cell lines. Review the per-cell-line panels when deciding whether the reference cohort represents a new study.</p>
<div id="fig-loo-summary" class="figure-anchor">

</div>
<p><img class="tutorial-figure" src="assets/figures/GSE122380_loo_summary.png" alt="Predicted versus observed differentiation day for every held-out sample." style="width:96%;"></p>
<div class="tutorial-figure-caption">
<strong>Figure 9.</strong> Predicted versus observed differentiation day for all held-out samples. The dashed line is identity; the solid line is an ordinary least-squares summary.
</div>
<p>The identity line represents exact timing prediction. The fitted line summarizes association in this cohort; it does not replace the sample-level error measures.</p>
<p>For held-out sample <span class="math inline">\(i\)</span>, absolute prediction error is</p>
<p><span class="math display">\[
e_i = |\widehat{t}_i - t_i|.
\tag{5}
\]</span></p>
<p>Figure 10 summarizes the mean absolute error at each observed day. The error bars show one standard deviation across held-out samples at that day.</p>
<div id="fig-loo-timepoint-accuracy" class="figure-anchor">

</div>
<p><img class="tutorial-figure" src="assets/figures/GSE122380_loo_timepoint_accuracy.png" alt="Mean absolute held-out prediction error by observed differentiation day, with standard-deviation error bars." style="width:82%;"></p>
<div class="tutorial-figure-caption">
<strong>Figure 10.</strong> Absolute held-out prediction error by day. Lower values indicate closer timing predictions.
</div>
<p>Compare day-specific errors with the overall summary when assessing the reference time course.</p>
</div>
<div id="interpreting-results" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">6</span> Interpreting results<a href="#interpreting-results" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="interpreting-scores" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Interpreting scores<a href="#interpreting-scores" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Use the sample-level <code>timing_fit$scores</code> table to read the result:</p>
<ul>
<li><code>predicted_time</code> gives the sample’s position on the original reference-time scale.</li>
<li><code>differentiation_score</code> rescales that position so the earliest and latest reference times are 0 and 1.</li>
<li><code>squared_distance</code> measures how close the sample is to its nearest trajectory segment in the retained PCA space.</li>
</ul>
<p>The score is relative to the selected reference. A score of 0.5 means that the predicted time is halfway between the earliest and latest reference times after endpoint scaling; it does not mean that the sample has reached half of an absolute biological process. Read squared distance with the score. A large value means that the sample is far from the learned reference path; compare it with reference-sample distances before interpreting the score.</p>
</div>
<div id="adapting-maturation-score" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> Adapting maturation score<a href="#adapting-maturation-score" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Use an independent reference cohort with known timepoints to select temporal genes and fit the trajectory. Then project new samples without refitting the PCA or temporal-gene set on those samples. Pass the reference sample IDs through <code>reference_samples</code>:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a>timing_fit <span class="ot">&lt;-</span> <span class="fu">score_differentiation_timing</span>(</span>
<span id="cb5-2"><a href="#cb5-2" tabindex="-1"></a>  <span class="at">expression_matrix =</span> expression_matrix,</span>
<span id="cb5-3"><a href="#cb5-3" tabindex="-1"></a>  <span class="at">metadata =</span> metadata,</span>
<span id="cb5-4"><a href="#cb5-4" tabindex="-1"></a>  <span class="at">temporal_genes =</span> temporal_genes,</span>
<span id="cb5-5"><a href="#cb5-5" tabindex="-1"></a>  <span class="at">reference_samples =</span> reference_sample_ids</span>
<span id="cb5-6"><a href="#cb5-6" tabindex="-1"></a>)</span></code></pre></div>
<p>Before comparing scores, check that gene identifiers and sample identifiers match, expression values use the same normalization convention, and the reference spans the relevant time range. Compare new-sample squared distances with the reference-sample distances. If the biological process or batch structure differs from the reference, fit a new reference model rather than treating the score as directly comparable.</p>
</div>
</div>
<div id="references" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">7</span> References<a href="#references" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<ol style="list-style-type: decimal">
<li>Love MI, Huber W, Anders S. Moderated estimation of fold change and dispersion for RNA-seq data with DESeq2. <em>Genome Biology</em>. 2014;15:550. <a href="https://doi.org/10.1186/s13059-014-0550-8">doi:10.1186/s13059-014-0550-8</a></li>
<li>Robinson MD, McCarthy DJ, Smyth GK. edgeR: a Bioconductor package for differential expression analysis of digital gene expression data. <em>Bioinformatics</em>. 2010;26(1):139–140. <a href="https://doi.org/10.1093/bioinformatics/btp616">doi:10.1093/bioinformatics/btp616</a></li>
<li>Strober BJ, Elorbany R, Rhodes K, et al. Dynamic genetic regulation of gene expression during cellular differentiation. <em>Science</em>. 2019;364(6447):1287–1290. <a href="https://doi.org/10.1126/science.aaw0040">doi:10.1126/science.aaw0040</a></li>
<li><a href="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE122380">NCBI GEO accession GSE122380</a></li>
</ol>
</div>
<div id="session-information" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">8</span> Session information<a href="#session-information" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<pre><code>## R version 4.6.1 (2026-06-24)
## Platform: aarch64-apple-darwin23
## Running under: macOS Tahoe 26.5.1
## Matrix products: default
## BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib
## LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1
## locale:
## [1] C.UTF-8/C.UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8
## time zone: America/Chicago
## tzcode source: internal
## attached base packages:
## [1] grid      stats4    stats     graphics  grDevices utils     datasets
## [8] methods   base
## other attached packages:
##  [1] viridis_0.6.5               viridisLite_0.4.3
##  [3] systemfonts_1.3.2           scales_1.4.0
##  [5] ragg_1.5.2                  patchwork_1.3.2
##  [7] org.Hs.eg.db_3.23.1         ggrepel_0.9.8
##  [9] ggplot2_4.0.3               edgeR_4.10.1
## [11] limma_3.68.4                DESeq2_1.52.0
## [13] SummarizedExperiment_1.42.0 MatrixGenerics_1.24.0
## [15] matrixStats_1.5.0           GenomicRanges_1.64.0
## [17] Seqinfo_1.2.0               ComplexHeatmap_2.28.0
## [19] clusterProfiler_4.20.0      circlize_0.4.18
## [21] AnnotationDbi_1.74.0        IRanges_2.46.0
## [23] S4Vectors_0.50.1            Biobase_2.72.0
## [25] BiocGenerics_0.58.1         generics_0.1.4
## [27] bookdown_0.47
## loaded via a namespace (and not attached):
##   [1] RColorBrewer_1.1-3      rstudioapi_0.19.0       jsonlite_2.0.0
##   [4] shape_1.4.6.1           tidydr_0.0.6            magrittr_2.0.5
##   [7] magick_2.9.1            ggtangle_0.1.2          rmarkdown_2.31
##  [10] farver_2.1.2            GlobalOptions_0.1.4     fs_2.1.0
##  [13] vctrs_0.7.3             Cairo_1.7-0             memoise_2.0.1
##  [16] ggtree_4.2.0            htmltools_0.5.9         S4Arrays_1.12.0
##  [19] SparseArray_1.12.2      gridGraphics_0.5-1      sass_0.4.10
##  [22] bslib_0.11.0            htmlwidgets_1.6.4       plyr_1.8.9
##  [25] httr2_1.3.0             cachem_1.1.0            igraph_2.3.3
##  [28] lifecycle_1.0.5         iterators_1.0.14        pkgconfig_2.0.3
##  [31] Matrix_1.7-5            R6_2.6.1                fastmap_1.2.0
##  [34] gson_0.2.0              clue_0.3-68             digest_0.6.39
##  [37] aplot_0.3.1             enrichplot_1.32.0       colorspace_2.1-3
##  [40] ggnewscale_0.5.2        aisdk_1.4.12            textshaping_1.0.5
##  [43] RSQLite_3.53.3          labeling_0.4.3          mgcv_1.9-4
##  [46] abind_1.4-8             httr_1.4.8              polyclip_1.10-7
##  [49] compiler_4.6.1          bit64_4.8.2             fontquiver_0.2.1
##  [52] withr_3.0.3             doParallel_1.0.17       S7_0.2.2
##  [55] BiocParallel_1.46.0     DBI_1.3.0               ggforce_0.5.0
##  [58] R.utils_2.13.0          MASS_7.3-65             DelayedArray_0.38.2
##  [61] rappdirs_0.3.4          rjson_0.2.23            tools_4.6.1
##  [64] otel_0.2.0              ape_5.8-1               scatterpie_0.2.6
##  [67] R.oo_1.27.1             glue_1.8.1              callr_3.8.0
##  [70] nlme_3.1-169            R.cache_0.17.0          GOSemSim_2.38.3
##  [73] cluster_2.1.8.2         reshape2_1.4.5          gtable_0.3.6
##  [76] R.methodsS3_1.8.2       tidyr_1.3.2             XVector_0.52.0
##  [79] foreach_1.5.2           pillar_1.11.1           stringr_1.6.0
##  [82] yulab.utils_0.2.4       splines_4.6.1           dplyr_1.2.1
##  [85] tweenr_2.0.3            treeio_1.36.1           lattice_0.22-9
##  [88] bit_4.6.0               tidyselect_1.2.1        locfit_1.5-9.12
##  [91] fontLiberation_0.1.0    GO.db_3.23.1            Biostrings_2.80.1
##  [94] knitr_1.51              gridExtra_2.3.1         fontBitstreamVera_0.1.1
##  [97] xfun_0.60               statmod_1.5.2           stringi_1.8.7
## [100] lazyeval_0.2.3          ggfun_0.2.1             yaml_2.3.12
## [103] evaluate_1.0.5          codetools_0.2-20        gdtools_0.5.1
## [106] tibble_3.3.1            qvalue_2.44.0           BiocManager_1.30.27
## [109] ggplotify_0.1.3         cli_3.6.6               jquerylib_0.1.4
## [112] processx_3.9.0          styler_1.11.0           dichromat_2.0-0.1
## [115] Rcpp_1.1.2              png_0.1-9               parallel_4.6.1
## [118] blob_1.3.0              DOSE_4.6.0              tidytree_0.4.8
## [121] ggiraph_0.9.6           enrichit_0.2.0          purrr_1.2.2
## [124] crayon_1.5.3            GetoptLong_1.1.1        rlang_1.3.0
## [127] KEGGREST_1.52.2</code></pre>

</div>
            </section>

          </div>
        </div>
      </div>


    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": null,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "none",
    "scroll_highlight": false
  },
  "toolbar": {
    "position": "static"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
